// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsqxdfvybuentpjdojjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzcXhkZnZ5YnVlbnRwamRvamp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDUxMzIsImV4cCI6MjA3Mzg4MTEzMn0.x1du-KWf9m_hFUcerul7GOM4dXucCHw1H0PdjthNmn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});